Add draft mode support
changesets/action pull request #258
Opened 2023-01-25 18:23 UTC by tom-sherman

Closes #257

2023-01-25 18:23 UTC, tom-sherman commented
Docs incoming...

2023-04-21 18:47 UTC, cruzdanilo approved these changes

2023-04-21 18:49 UTC, cruzdanilo commented
is there something blocking this pr?

2024-02-07 15:56 UTC, svenvoskamp commented
Any updates on this? Would like to use this functionality

2024-12-01 13:55 UTC, Fart10 approved these changes
🤗

2025-01-30 08:23 UTC, nickfujita commented
Ping from 2025. Any chance we can get this merged in? I think it would provide a nicer solution to the issue of the Version Packages pr not triggering `pull_request` than closing and re-opening the PR.
https://github.com/changesets/action/issues/187

2025-03-31 22:11 UTC, altano commented
I know this probably isn't getting merged anytime soon, but I just wanted to mention that, taking a cue from https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs, we probably want the PR to always be set back to a draft when it's updated. So if the versions change it goes back to draft, and if the workflow has `on: ready_for_review`, it'll be retriggered everytime you the PR is updated and you set it back to ready for review.

2026-01-29 10:03 UTC, vitorhsb requested changes

2026-01-29 10:03 UTC, vitorhsb commented on src/run.ts
> +      draft: createPrAsDraft,
Should have the same validation when updating the PR in the block below.

Or create a new property for converting back to draft: `updatePrConvertToDraft`

2026-03-16 12:57 UTC, tom-sherman commented on src/run.ts
> +      draft: createPrAsDraft,
I don't think this setting should edit the draft status if the PR already exists, that would be a separate feature request/option.

2026-04-01 06:58 UTC, Andarist commented
/release-pr

2026-04-01 07:05 UTC, Andarist commented
I'd appreciate it if somebody could test this out in their project using the above build. This would certainly allow me to ship this faster.

2026-04-02 11:12 UTC, tom-sherman commented
hey @Andarist thanks for picking this up! I tested it on my project (internal so can't share, sorry!) and it correctly opened the PR as draft in "create" mode. From my POV this looks good to release.

2026-04-07 14:36 UTC, tom-sherman commented
FYI this doesn't provide a complete solution for #187 because if you mark the PR as ready and changesets updates the PR (because something else got merged to main) the required checks won't run. Not a problem with this change, just a caveat on how it relates to that issue.

2026-05-07 09:35 UTC, merged

2026-05-07 09:38 UTC, Andarist commented
@tom-sherman a nice workaround for this might be to use an internal GitHub app and use its token like [here](https://github.com/changesets/action/blob/f5dbf72f96949cb0daf45152f0f63062df70e97d/.github/workflows/publish.yml#L44-L52). You don't even have to host an actual application anywhere, just put the app's private key into the secrets and ensure the app has the needed permissions and the secret can't be used in unsafe contexts etc

2026-05-07 10:36 UTC, AriPerkkio commented
@Andarist just today after this PR I started to see similar issues like #187. Hadn't seen any of those before. Could this PR be related? It was working fine earlier this week. https://github.com/chromaui/chromatic-e2e/pull/344

2026-05-07 11:01 UTC, Andarist commented
@AriPerkkio I don't see any checks executed in [this PR](https://github.com/chromaui/chromatic-e2e/pull/336/changes/cfabeca3ebbb81a84e675256ad223cbc96aecd63) from 3 days ago:
<img width="736" height="225" alt="Screenshot 2026-05-07 at 13 01 27" src="https://github.com/user-attachments/assets/3ab24083-8e25-452d-bd2e-7ce4d665636c" />

2026-06-02 10:55 UTC, Frank122480 reviewed
:-)

2026-06-02 10:58 UTC, Frank122480 reviewed
Works for me